### ISSUE TITLE
Epic RPG Ruby Hype Bot

### ISSUE THREAD

**Issue by Tdevilla** [jeremybumsted/duckworth#1]
I need a hype man for my ruby collecting. I request Duckworth fulfill the role.

Simply put, I need someone to immediately spam the following gif when I obtain a ruby from any mining, drilling, spelunking, or other resource collecting activities:

https://tenor.com/view/impressed-antonio-banderas-gif-9592821

Please note, this gif should not be sent/used when obtaining a ruby in any other means, such as a lootbox or trading.

This issue is important because I lack a certain amount of self-confidence and the additional affirmation from a hype bot whenever my luck pulls through would do wonders in my lifetime. Please see it done.

**Comment by jeremybumsted** [comment]
Issue no longer applies as RPG is no longer used on the server
